export const allImages = {
    forest: {
        name: 'Forest',
        shortDescription: "Forest lorem ipsum",
        longDescription: "Forest cocktail glendullan lime rickey kir bronx joker murphy's smoky martini brandy daisy ketel one. Kirsch irish flag, glentauchers, 'cheeky vimto!' Corn n' oil coronet vso dewar's scotch whisky paradise zombie porto flip paddy. Harper's my fair lady, 'glenlivet brave bull, cosmopolitan, sangría aultmore.' French 75 horse's neck screwdriver ron rico polish martini balmenach glendronach cape cod tequila slammer wild turkey?",
        images: [
            {
                name: 'Forest 1',
                gallery: "forest",
                tags: ['forest', 'adventure'],
                urlContent: 'img/photos/content/forest_01.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_01.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_01.jpg',
            },
            {
                name: 'Forest 2',
                gallery: "forest",
                tags: ['forest'],
                urlContent: 'img/photos/content/forest_02.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_02.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_02.jpg',
            },
            {
                name: 'Forest 3',
                gallery: "forest",
                tags: ['forest', 'adventure'],
                urlContent: 'img/photos/content/forest_03.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_03.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_03.jpg',
            },
            {
                name: 'Forest 4',
                gallery: "forest",
                tags: ['forest', 'adventure'],
                urlContent: 'img/photos/content/forest_04.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_04.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_04.jpg',
            },
            {
                name: 'Forest 5',
                gallery: "forest",
                tags: ['forest', 'adventure'],
                urlContent: 'img/photos/content/forest_05.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_05.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_05.jpg',
            },
            {
                name: 'Forest 6',
                gallery: "forest",
                tags: ['forest', 'adventure'],
                urlContent: 'img/photos/content/forest_06.jpg',
                urlSlideshow: 'img/photos/slideshow/forest_06.jpg',
                urlThumbnails: 'img/photos/thumbnails/forest_06.jpg',
            },
        ]
    },
    neon: {
        name: 'Neon',
        shortDescription: "Neon lorem ipsum",
        description: "Neon cocktail glendullan lime rickey kir bronx joker murphy's smoky martini brandy daisy ketel one. Kirsch irish flag, glentauchers, 'cheeky vimto!' Corn n' oil coronet vso dewar's scotch whisky paradise zombie porto flip paddy. Harper's my fair lady, 'glenlivet brave bull, cosmopolitan, sangría aultmore.' French 75 horse's neck screwdriver ron rico polish martini balmenach glendronach cape cod tequila slammer wild turkey?",
        images: [
            {
                name: 'Neon 1',
                gallery: "neon",
                tags: ['neon', 'adventure'],
                urlContent: 'img/photos/content/neon_01.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_01.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_01.jpg',
            },
            {
                name: 'Neon 2',
                gallery: "neon",
                tags: ['neon'],
                urlContent: 'img/photos/content/neon_02.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_02.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_02.jpg',
            },
            {
                name: 'Neon 3',
                gallery: "neon",
                tags: ['neon', 'adventure'],
                urlContent: 'img/photos/content/neon_03.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_03.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_03.jpg',
            },
            {
                name: 'Neon 4',
                gallery: "neon",
                tags: ['neon', 'adventure'],
                urlContent: 'img/photos/content/neon_04.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_04.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_04.jpg',
            },
            {
                name: 'Neon 5',
                gallery: "neon",
                tags: ['neon', 'adventure'],
                urlContent: 'img/photos/content/neon_05.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_05.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_05.jpg',
            },
            {
                name: 'Neon 6',
                gallery: "neon",
                tags: ['neon', 'adventure'],
                urlContent: 'img/photos/content/neon_06.jpg',
                urlSlideshow: 'img/photos/slideshow/neon_06.jpg',
                urlThumbnails: 'img/photos/thumbnails/neon_06.jpg',
            },
        ]
    },
    people: {
        name: 'People',
        longDescription: "People cocktail glendullan lime rickey kir bronx joker murphy's smoky martini brandy daisy ketel one. Kirsch irish flag, glentauchers, 'cheeky vimto!' Corn n' oil coronet vso dewar's scotch whisky paradise zombie porto flip paddy. Harper's my fair lady, 'glenlivet brave bull, cosmopolitan, sangría aultmore.' French 75 horse's neck screwdriver ron rico polish martini balmenach glendronach cape cod tequila slammer wild turkey?",
        shortDescription: "People lorem ipsum",
        images: [
            {
                name: 'People 1',
                gallery: "people",
                tags: ['people', 'adventure'],
                urlContent: 'img/photos/content/people_01.jpg',
                urlSlideshow: 'img/photos/slideshow/people_01.jpg',
                urlThumbnails: 'img/photos/thumbnails/people_01.jpg',
            },
            {
                name: 'People 2',
                gallery: "people",
                tags: ['people'],
                urlContent: 'img/photos/content/people_02.jpg',
                urlSlideshow: 'img/photos/slideshow/people_02.jpg',
                urlThumbnails: 'img/photos/thumbnails/people_02.jpg',
            },
            {
                name: 'People 3',
                gallery: "people",
                tags: ['people', 'adventure', 'your mama'],
                urlContent: 'img/photos/content/people_03.jpg',
                urlSlideshow: 'img/photos/slideshow/people_03.jpg',
                urlThumbnails: 'img/photos/thumbnails/people_03.jpg',
            },
            {
                name: 'People 4',
                gallery: "people",
                tags: ['people'],
                urlContent: 'img/photos/content/people_04.jpg',
                urlSlideshow: 'img/photos/slideshow/people_04.jpg',
                urlThumbnails: 'img/photos/thumbnails/people_04.jpg',
            },
            {
                name: 'People 5',
                gallery: "people",
                tags: ['people'],
                urlContent: 'img/photos/content/people_05.jpg',
                urlSlideshow: 'img/photos/slideshow/people_05.jpg',
                urlThumbnails: 'img/photos/thumbnails/people_05.jpg',
            }
        ]
    },
    toronto: {
        name: 'Toronto',
        shortDescription: 'Toronto lorem ipsum',
        longDescription: "Toronto cocktail glendullan lime rickey kir bronx joker murphy's smoky martini brandy daisy ketel one. Kirsch irish flag, glentauchers, 'cheeky vimto!' Corn n' oil coronet vso dewar's scotch whisky paradise zombie porto flip paddy. Harper's my fair lady, 'glenlivet brave bull, cosmopolitan, sangría aultmore.' French 75 horse's neck screwdriver ron rico polish martini balmenach glendronach cape cod tequila slammer wild turkey?",
        images: [
            {
                name: 'Toronto 1',
                gallery: "toronto",
                tags: ['toronto', 'adventure'],
                urlContent: 'img/photos/content/toronto_01.jpg',
                urlSlideshow: 'img/photos/slideshow/toronto_01.jpg',
                urlThumbnails: 'img/photos/thumbnails/toronto_01.jpg',
            },
            {
                name: 'Toronto 2',
                gallery: "toronto",
                tags: ['toronto'],
                urlContent: 'img/photos/content/toronto_02.jpg',
                urlSlideshow: 'img/photos/slideshow/toronto_02.jpg',
                urlThumbnails: 'img/photos/thumbnails/toronto_02.jpg',
            },
            {
                name: 'Toronto 3',
                gallery: "toronto",
                tags: ['toronto', 'adventure'],
                urlContent: 'img/photos/content/toronto_03.jpg',
                urlSlideshow: 'img/photos/slideshow/toronto_03.jpg',
                urlThumbnails: 'img/photos/thumbnails/toronto_03.jpg',
            },
            {
                name: 'Toronto 4',
                gallery: "toronto",
                tags: ['toronto'],
                urlContent: 'img/photos/content/toronto_04.jpg',
                urlSlideshow: 'img/photos/slideshow/toronto_04.jpg',
                urlThumbnails: 'img/photos/thumbnails/toronto_04.jpg',
            }
        ]
    },
}